# Задание 1


Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np 

In [2]:
number = int(input())
a = np.arange(number)
a = a[::-1]
a

6


array([5, 4, 3, 2, 1, 0])

# Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [16]:
N = int(input())
print('____________')
a = np.arange(0, N, 1)
a = a[::-1]
print(np.diag(a))
print('____________')
print(np.diag(a).sum())


6
____________
[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
____________
15


# Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [6]:
from numpy import linalg
a = np.array( [ [4, 2, 0], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
print(linalg.solve(a, b))
print(np.allclose( np.dot(a, linalg.solve(a, b)), b ))

[-1.2   4.4  -6.25]
True


# Задание 4

Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [21]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
list_ = []

In [22]:
def cosine(a, b):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot(a, b) / ( aLength * bLength )

In [29]:
for i in users_stats:
    list_.append(cosine(i, b=next_user_stats))
    
print(f'На пользователя {next_user_stats} больше всего похож {users_stats[list_.index(max(list_))]}')

На пользователя [0 1 2 0 0 0] больше всего похож [0 1 1 0 0 0]
